### ISSUE TITLE
BUG: System requirements link fix

### ISSUE THREAD

**Issue by jeffsikes** [superseriousbusiness/gotosocial-landingpage#4]
Noticed that the system requirements link on the landing page isn't displaying what I assume is expected. This is found in the "Why use GoToSocial and not Mastodon or [xyz] other software?" section. 

See [existing link](https://docs.gotosocial.org/en/latest/installation_guide/#server-vps). I believe it should be pointing to this new location [here](https://docs.gotosocial.org/en/latest/getting_started/#server-vps).

It's taken longer to write this up than to make the change, but I'm just getting my feet wet with open source and felt this was a good learning opportunity. Will submit a pull request momentarily. Thanks!

**Comment by tsmethurst** [comment]
Thank you for fixing this for us! :)
